version: '3.8'

services:
  reverse-proxy:
    image: nginx:stable-perl
    
  gql:

  eventstore:
    build: .

  eventdb:
    image: postgres:17
    volumes:
      - postgres:/dev/shm
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  - postgres
  